sudo: required

services:
  - docker

language: go
before_install:
  - sudo apt-get update
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

cache:
  directories:
    - vendor
