version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - mkdir bin
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - make deps
      - go build -o bin/health ./handlers/health
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - bin/health
