version: 0.2

env:
  variables:
    # This S3 bucket will be used to store the packaged Lambda deployment bundle.
    # Make sure to provide a valid S3 bucket name (it must exist already).
    # The AWS CodeBuild IAM role must allow write access to it.
    PACKAGE: "github.com/PolarGeospatialCenter/inventory"

phases:

  install:
    commands:

      # AWS Codebuild Go images use /go for the $GOPATH so let's copy our
      # application source code into that directory structure.
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      #- cp "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"

      # Print all environment variables (handy for AWS CodeBuild logs)
      - env

      - go get github.com/golang/dep/cmd/dep

  pre_build:
    commands:

      # Make sure we're in the project directory within our GOPATH
      - cd "/go/src/${PACKAGE}"

      # Make Bin Dir
      - mkdir bin

  build:
    commands:

      # Build our go application
      - GOPATH=/go make build
      - aws cloudformation package --template-file template.yml --s3-bucket ${S3_BUCKET} --output-template-file packaged.yml

cache:
  paths:
    - vendor/**/*

artifacts:
  files:
    - packaged.yml
