AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.

Resources:
  NodeTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: last_updated
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: last_updated
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: inventory_nodes
      Tags:
        - Key: application
          Value: inventory
  MACLookupTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: last_updated
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: last_updated
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: inventory_node_mac_lookup
      Tags:
        - Key: application
          Value: inventory
  SystemTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: last_updated
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: last_updated
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: inventory_systems
      Tags:
        - Key: application
          Value: inventory
  NetworkTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: last_updated
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: last_updated
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: inventory_networks
      Tags:
        - Key: application
          Value: inventory
  HealthCheck:
    Type: AWS::Serverless::Function
    Properties:
      Handler: health
      CodeUri: bin/
      Runtime: go1.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /health
            Method: get
  NodeLookup:
    Type: AWS::Serverless::Function
    Properties:
      Handler: node
      CodeUri: bin/
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /node
            Method: get
  NetworkLookup:
    Type: AWS::Serverless::Function
    Properties:
      Handler: network
      CodeUri: bin/
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /network
            Method: get
  SystemLookup:
    Type: AWS::Serverless::Function
    Properties:
      Handler: system
      CodeUri: bin/
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /system
            Method: get
  NodeConfigLookup:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nodeconfig
      CodeUri: bin/
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /nodeconfig
            Method: get
