AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.

Resources:
  HealthCheck:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/health
      Runtime: go1.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /health
            Method: get
  Node:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/node
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /node
            Method: get
